#! /bin/sh

xsetroot -cursor_name left_ptr &
picom -b &
unclutter -idle 2 &
greenclip daemon &
/home/inabsentia81/.config/wpg/wp_init.sh &
polybar wpgtk &
bash /home/inabsentia81/.config/bspwm/bspwm_colors.sh &
blueberry-tray &
nm-applet &
volumeicon &
sxhkd &

# You need to change this if you have multiple monitors
#bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor -d     web term droid tge bio death play music film bt

bspc config border_width          0
bspc config window_gap            15
bspc config top_padding           20
bspc config right_padding         5
bspc config bottom_padding        5
bspc config left_padding          5
bspc config split_ratio           0.52
bspc config borderless_monocle    false
bspc config gapless_monocle       true
bspc config paddingless_monocle   true 
bspc config focus_follows_pointer true
bspc config border_radius         10
bspc config pointer_modifier      mod1
bspc config click_to_focus        false
bspc config focus_follows_pointer true
bspc config pointer_action1       move
bspc config pointer_action2       resize_side
bspc config pointer_action3       resize_corner

bspc rule -a woeusbgui state=floating center=on
bspc rule -a blueberry state=floating center=on
bspc rule -a wpgtk state=floating center=on
bspc rule -a nitrogen state=floating
bspc rule -a feh state=floating
bspc rule -a krita state=floating
bspc rule -a blender state=floating
bspc rule -a obs state=floating
bspc rule -a sxiv state=pseudo_tiled
bspc rule -a mpv state=pseudo_tiled

